name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [2.7, 3.5, 3.7]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install package and dependencies
      run: |
        python -m pip install --upgrade pip
        python setup.py sdist
        VRS=$(python setup.py -V)
        pip install --upgrade dist/dmf24-pyprocess-$VRS.tar.gz
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=30 --ignore=E225,E302,E265,E266,E305 --max-line-length=127 --statistics
    - name: doctest
      run: |
        python process/__init__.py
